package telas;

//import curso.view.JIFCadastroCurso;
//import disciplina.view.JIFCadastroDisciplina;
//import professor.view.JIFCadastroProfessor;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import professor.view.JIFVisualizarProfessor;
//import usuario.view.JIFCadastroUsuario;
//import disciplina.view.JIFVisualizarDisciplina;
//import usuario.view.JIFVisualizarUsuario;

/**
 *
 * @author GRUPO KERNEL
 */
public class JFPrincipal extends javax.swing.JFrame {

    public void iconeDaJanela() {
        setIconImage(new ImageIcon(getClass().getResource("/imagens/icons/sgh_24.png")).getImage());
    }

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
       // initComponents();
        iconeDaJanela();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JSeparator();
        jDPPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMISair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMICursoC = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMIDisciplinasC = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMIModulosC = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMITurmasC = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMIProfessoresC = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMIRestricoesC = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMIUsuariosC = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMIDisciplinasV = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMIModulosV = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMITurmasV = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMIProfessoresV = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMIUsuariosV = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMIGradeHorariaV = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMIAjuda = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMISobre = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("jMenu5");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenuItem3.setText("jMenuItem3");

        setTitle("Sistema de Grade Horária - SGH");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SGH5.png"))); // NOI18N

        javax.swing.GroupLayout jDPPrincipalLayout = new javax.swing.GroupLayout(jDPPrincipal);
        jDPPrincipal.setLayout(jDPPrincipalLayout);
        jDPPrincipalLayout.setHorizontalGroup(
            jDPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDPPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDPPrincipalLayout.setVerticalGroup(
            jDPPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDPPrincipalLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(133, 133, 133))
        );
        jDPPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setMnemonic('i');
        jMenu1.setText("Início");

        jMISair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMISair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/sair_32.png"))); // NOI18N
        jMISair.setMnemonic('s');
        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMenu1.add(jMISair);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('c');
        jMenu2.setText("Cadastros");

        jMICursoC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        jMICursoC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/curso_16.png"))); // NOI18N
        jMICursoC.setMnemonic('s');
        jMICursoC.setText("Curso");
        jMICursoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICursoCActionPerformed(evt);
            }
        });
        jMenu2.add(jMICursoC);
        jMenu2.add(jSeparator2);

        jMIDisciplinasC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMIDisciplinasC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/livros_16.png"))); // NOI18N
        jMIDisciplinasC.setMnemonic('d');
        jMIDisciplinasC.setText("Disciplinas");
        jMIDisciplinasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDisciplinasCActionPerformed(evt);
            }
        });
        jMenu2.add(jMIDisciplinasC);
        jMenu2.add(jSeparator3);

        jMIModulosC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMIModulosC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/cubo_16.png"))); // NOI18N
        jMIModulosC.setMnemonic('m');
        jMIModulosC.setText("Módulos");
        jMenu2.add(jMIModulosC);
        jMenu2.add(jSeparator4);

        jMITurmasC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK));
        jMITurmasC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/turmas_24.png"))); // NOI18N
        jMITurmasC.setMnemonic('t');
        jMITurmasC.setText("Turmas");
        jMenu2.add(jMITurmasC);
        jMenu2.add(jSeparator5);

        jMIProfessoresC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_MASK));
        jMIProfessoresC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/professor_16.png"))); // NOI18N
        jMIProfessoresC.setMnemonic('p');
        jMIProfessoresC.setText("Professores");
        jMIProfessoresC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProfessoresCActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProfessoresC);
        jMenu2.add(jSeparator6);

        jMIRestricoesC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.ALT_MASK));
        jMIRestricoesC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/exclamacao_16.png"))); // NOI18N
        jMIRestricoesC.setMnemonic('r');
        jMIRestricoesC.setText("Restrições");
        jMenu2.add(jMIRestricoesC);
        jMenu2.add(jSeparator7);

        jMIUsuariosC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.ALT_MASK));
        jMIUsuariosC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/usuarios_16.png"))); // NOI18N
        jMIUsuariosC.setMnemonic('u');
        jMIUsuariosC.setText("Usuários");
        jMIUsuariosC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIUsuariosCActionPerformed(evt);
            }
        });
        jMenu2.add(jMIUsuariosC);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('v');
        jMenu3.setText("Visualizações");

        jMIDisciplinasV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIDisciplinasV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/livros_16.png"))); // NOI18N
        jMIDisciplinasV.setMnemonic('d');
        jMIDisciplinasV.setText("Disciplinas");
        jMIDisciplinasV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIDisciplinasVActionPerformed(evt);
            }
        });
        jMenu3.add(jMIDisciplinasV);
        jMenu3.add(jSeparator9);

        jMIModulosV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIModulosV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/cubo_16.png"))); // NOI18N
        jMIModulosV.setMnemonic('m');
        jMIModulosV.setText("Módulos");
        jMenu3.add(jMIModulosV);
        jMenu3.add(jSeparator10);

        jMITurmasV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMITurmasV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/turmas_24.png"))); // NOI18N
        jMITurmasV.setMnemonic('t');
        jMITurmasV.setText("Turmas");
        jMenu3.add(jMITurmasV);
        jMenu3.add(jSeparator11);

        jMIProfessoresV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIProfessoresV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/professor_16.png"))); // NOI18N
        jMIProfessoresV.setMnemonic('p');
        jMIProfessoresV.setText("Professores");
        jMIProfessoresV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProfessoresVActionPerformed(evt);
            }
        });
        jMenu3.add(jMIProfessoresV);
        jMenu3.add(jSeparator12);

        jMIUsuariosV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIUsuariosV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/usuarios_16.png"))); // NOI18N
        jMIUsuariosV.setMnemonic('u');
        jMIUsuariosV.setText("Usuários");
        jMIUsuariosV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIUsuariosVActionPerformed(evt);
            }
        });
        jMenu3.add(jMIUsuariosV);
        jMenu3.add(jSeparator13);

        jMIGradeHorariaV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMIGradeHorariaV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/grade_horaria_16.png"))); // NOI18N
        jMIGradeHorariaV.setMnemonic('g');
        jMIGradeHorariaV.setText("Grade Horária");
        jMIGradeHorariaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGradeHorariaVActionPerformed(evt);
            }
        });
        jMenu3.add(jMIGradeHorariaV);

        jMenuBar1.add(jMenu3);

        jMenu9.setMnemonic('a');
        jMenu9.setText("Ajuda");

        jMIAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMIAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/ajuda_16.png"))); // NOI18N
        jMIAjuda.setMnemonic('a');
        jMIAjuda.setText("Ajuda");
        jMenu9.add(jMIAjuda);
        jMenu9.add(jSeparator14);

        jMISobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMISobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/sobre_16.png"))); // NOI18N
        jMISobre.setMnemonic('s');
        jMISobre.setText("Sobre");
        jMISobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISobreActionPerformed(evt);
            }
        });
        jMenu9.add(jMISobre);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
        sair();
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMIGradeHorariaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGradeHorariaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIGradeHorariaVActionPerformed

    private void jMIDisciplinasVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDisciplinasVActionPerformed
       JIFVisualizarDisciplina disciplina = new JIFVisualizarDisciplina();
        configurarTela(disciplina);
    }//GEN-LAST:event_jMIDisciplinasVActionPerformed

    private void jMISobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISobreActionPerformed
        new JDSobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMISobreActionPerformed

    private void jMIUsuariosCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIUsuariosCActionPerformed
        JIFCadastroUsuario usuario = new JIFCadastroUsuario();
        configurarTela(usuario);
    }//GEN-LAST:event_jMIUsuariosCActionPerformed

    private void jMICursoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICursoCActionPerformed
        JIFCadastroCurso curso = new JIFCadastroCurso();
        configurarTela(curso);
    }//GEN-LAST:event_jMICursoCActionPerformed

    private void jMIProfessoresCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProfessoresCActionPerformed
        JIFCadastroProfessor professor = new JIFCadastroProfessor();
        configurarTela(professor);
        
    }//GEN-LAST:event_jMIProfessoresCActionPerformed

    private void jMIDisciplinasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIDisciplinasCActionPerformed
        JIFCadastroDisciplina disciplina = new JIFCadastroDisciplina();
        configurarTela(disciplina);
    }//GEN-LAST:event_jMIDisciplinasCActionPerformed

    private void jMIProfessoresVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProfessoresVActionPerformed
        JIFVisualizarProfessor professor = new JIFVisualizarProfessor();
       configurarTela(professor);
    }//GEN-LAST:event_jMIProfessoresVActionPerformed

    private void jMIUsuariosVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIUsuariosVActionPerformed
        JIFVisualizarUsuario usuario = new JIFVisualizarUsuario();
        configurarTela(usuario);
    }//GEN-LAST:event_jMIUsuariosVActionPerformed
*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMIAjuda;
    private javax.swing.JMenuItem jMICursoC;
    private javax.swing.JMenuItem jMIDisciplinasC;
    private javax.swing.JMenuItem jMIDisciplinasV;
    private javax.swing.JMenuItem jMIGradeHorariaV;
    private javax.swing.JMenuItem jMIModulosC;
    private javax.swing.JMenuItem jMIModulosV;
    private javax.swing.JMenuItem jMIProfessoresC;
    private javax.swing.JMenuItem jMIProfessoresV;
    private javax.swing.JMenuItem jMIRestricoesC;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMISobre;
    private javax.swing.JMenuItem jMITurmasC;
    private javax.swing.JMenuItem jMITurmasV;
    private javax.swing.JMenuItem jMIUsuariosC;
    private javax.swing.JMenuItem jMIUsuariosV;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables

    private void sair() {
        int o = JOptionPane.showConfirmDialog(rootPane, "Você deseja sair?", "Sair", JOptionPane.YES_NO_OPTION, WIDTH,
                (new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/sair_64.png"))));
        if (o == 0) {
            System.exit(0);
        }
    }

    private void configurarTela(javax.swing.JInternalFrame janela) {
        //JDesktopPane desktop = new JDesktopPane();
        //setContentPane(desktop);
        //janela = new javax.swing.JInternalFrame();
        janela.setVisible(true);
        jDPPrincipal.add(janela);
        try {
            janela.setMaximum(true);
            janela.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
