/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package disciplina.view;

import disciplina.bean.DisciplinaBean;
import disciplina.dao.DisciplinaDao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.DaoException;

/**
 *
 * @author GRUPO KERNEL
 */
public class JIFCadastroDisciplina extends javax.swing.JInternalFrame {

    DisciplinaDao disciplinaDao = null;

    /**
     * Creates new form JIFCadastroDisciplina
     */
    public JIFCadastroDisciplina() {
        initComponents();
        if (disciplinaDao == null) {
            disciplinaDao = new DisciplinaDao();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jTFNome = new javax.swing.JTextField();
        jTFSigla = new javax.swing.JTextField();
        jTFCargaHoraria = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBCadastrar = new javax.swing.JButton();
        jBPesquisar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();

        setTitle("Cadastro de Disciplina");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Código:");

        jLabel2.setText("Nome*:");

        jLabel3.setText("Sigla*:");

        jLabel4.setText("Carga Horária:");

        jTFCodigo.setEditable(false);

        jTFNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNomeKeyPressed(evt);
            }
        });

        jTFSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFSiglaKeyPressed(evt);
            }
        });

        jTFCargaHoraria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCargaHorariaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNome)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFSigla, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCargaHoraria))
                        .addGap(0, 219, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jBCadastrar.setMnemonic('C');
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBPesquisar.setMnemonic('P');
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBAlterar.setMnemonic('A');
        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBLimpar.setMnemonic('L');
        jBLimpar.setText("Limpar");
        jBLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimparActionPerformed(evt);
            }
        });

        jBExcluir.setMnemonic('E');
        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBFechar.setMnemonic('F');
        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jBCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFechar))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        fechar();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jBLimparActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTFNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jTFNomeKeyPressed

    private void jTFSiglaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSiglaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jTFSiglaKeyPressed

    private void jTFCargaHorariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCargaHorariaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            cadastrar();
        }
    }//GEN-LAST:event_jTFCargaHorariaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTFCargaHoraria;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFSigla;
    // End of variables declaration//GEN-END:variables

    private void fechar() {
        if (verificaPreenchido()) {
            int o = JOptionPane.showConfirmDialog(this, "Há dados preenchidos! Deseja realmente sair?", "Mensagem", JOptionPane.YES_OPTION);
            if (o == 0) {
                dispose();
            }
        } else {
            dispose();
        }
    }

    private boolean verificaPreenchido() {
        if (!(jTFNome.getText().isEmpty())
                || !(jTFSigla.getText().isEmpty())
                || !(jTFCargaHoraria.getText().isEmpty())) {
            return true;
        } else {
            return false;
        }
    }

    private void cadastrar() {
        DisciplinaBean disciplinaBean = populaDisciplinaBean();

        if (disciplinaBean != null) {
            try {
                if (disciplinaDao.inserir(disciplinaBean) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Disciplina cadastrada com sucesso!");
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar!");
                }
            } catch (DaoException ex) {
                Logger.getLogger(JIFCadastroDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private DisciplinaBean populaDisciplinaBean() {
        DisciplinaBean disciplinaBean;
        if (validaPreenchimento()) {
            disciplinaBean = new DisciplinaBean();

            disciplinaBean.setNome(jTFNome.getText());
            disciplinaBean.setSigla(jTFSigla.getText());
            if (!jTFCargaHoraria.getText().isEmpty()){
                disciplinaBean.setCargaHoraria(Integer.parseInt(jTFCargaHoraria.getText()));
            } else {
                disciplinaBean.setCargaHoraria(0);
            }
                
            return disciplinaBean;
        }
        return null;
    }

    private boolean validaPreenchimento() {
        if (jTFNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Nome");
            jTFNome.grabFocus();
            return false;
        } else if (jTFSigla.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe a Sigla");
            jTFSigla.grabFocus();
            return false;
        }
        return true;
    }

    private void limpar() {
        jTFCodigo.setText("");
        jTFNome.setText("");
        jTFSigla.setText("");
        jTFCargaHoraria.setText("");
    }

    private void pesquisar() {
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Informe o código da disciplina."));
        try {
            DisciplinaBean disciplinaBean = (DisciplinaBean) disciplinaDao.selecionar(codigo);
            if (disciplinaBean == null) {
                JOptionPane.showMessageDialog(rootPane, "Disciplina não encontrada!");
                limpar();
            } else {
                populaFormDisciplina(disciplinaBean);
            }
        } catch (DaoException ex) {
            Logger.getLogger(JIFCadastroDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void populaFormDisciplina(DisciplinaBean disciplinaBean) {
        jTFCodigo.setText(disciplinaBean.getId().toString());
        jTFNome.setText(disciplinaBean.getNome());
        jTFSigla.setText(disciplinaBean.getSigla());
        jTFCargaHoraria.setText(disciplinaBean.getCargaHoraria().toString());
    }

    private void alterar() {
        DisciplinaBean disciplinaBean = populaDisciplinaBean2();

        if (disciplinaBean != null) {
            try {
                if (disciplinaDao.alterar(disciplinaBean) != null) {
                    JOptionPane.showMessageDialog(rootPane, "Disciplina alterada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao alterar!");
                }
            } catch (DaoException ex) {
                Logger.getLogger(JIFCadastroDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private DisciplinaBean populaDisciplinaBean2() {
        DisciplinaBean disciplinaBean;
        if (validaPreenchimento()) {
            disciplinaBean = new DisciplinaBean();

            disciplinaBean.setId(Integer.parseInt(jTFCodigo.getText()));
            disciplinaBean.setNome(jTFNome.getText());
            disciplinaBean.setSigla(jTFSigla.getText());
            disciplinaBean.setCargaHoraria(Integer.parseInt(jTFCargaHoraria.getText()));

            return disciplinaBean;
        }
        return null;
    }

    private void excluir() {
        if (!jTFCodigo.getText().isEmpty()) {
            int codigo = Integer.parseInt(jTFCodigo.getText());
            try {
                if (disciplinaDao.excluir(codigo)) {
                    JOptionPane.showMessageDialog(rootPane, "Disciplina excluída!");
                    limpar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!");
                }
            } catch (DaoException ex) {
                Logger.getLogger(JIFCadastroDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!");
        }
    }
}
